### ISSUE TITLE
Fail to set up the python environment. Could you please report a result when K=2 and dim=256 with TransE score?

### ISSUE THREAD

**Issue by Zhang-Each** [junkangwu/DisenKGAT#1]
Good work! I tried to follow your work and run the code to do some new experiment on it but failed to set up the running environment after a long time struggle. It seems that the installation of PyG is a bit complex.
Could you please report the MRR and Hit@K results when K=2 and dim=256 with TransE score and FB15K-237 dataset? Can't thank you enough.

**Comment by junkangwu** [comment]
Hi,
Thanks for your attention. As for FB15K-237 dataset with transE score functions, this directory contains some related training logs. (https://github.com/junkangwu/DisenKGAT/tree/master/log). I think this result (dim=2*200=400) is slightly similar to dim=256. Of course, if you actually need accurate performance, please let me know. 

btw, dim=256 means K=2 * 128 or 2 * 256 ？
Best

**Comment by Zhang-Each** [comment]
> Hi, Thanks for your attention. As for FB15K-237 dataset with transE score functions, this directory contains some related training logs. (https://github.com/junkangwu/DisenKGAT/tree/master/log). I think this result (dim=2*200=400) is slightly similar to dim=256. Of course, if you actually need accurate performance, please let me know.
> 
> btw, dim=256 means K=2 * 128 or 2 * 256 ？ Best

Thank you! I ignored the log files. I think that's enough.

**Comment by junkangwu** [comment]
> > Hi, Thanks for your attention. As for FB15K-237 dataset with transE score functions, this directory contains some related training logs. (https://github.com/junkangwu/DisenKGAT/tree/master/log). I think this result (dim=2*200=400) is slightly similar to dim=256. Of course, if you actually need accurate performance, please let me know.
> > btw, dim=256 means K=2 * 128 or 2 * 256 ？ Best
> 
> Thank you! I ignored the log files. I think that's enough.

pleasure. I hope it helps.
